### ISSUE TITLE
Editing the attributes directly in Database Properties Panel

### ISSUE THREAD

**Issue by Achuan-2** [Macavity/siyuan-database-properties-panel#11]
it would be nice if this plugin can support editing the attributes directly in Database Properties Panel

**Comment by Macavity** [comment]
I know, that is a feature I want as well 😄

**Comment by Achuan-2** [comment]
ref： https://github.com/TransMux/SiYuan-Attributes-Panel/blob/48ece4f7268620e49bb2254794e662c099d4d74c/src/components/DbRow.vue#L139
API:
```js
// number
let res = await request("/api/av/setAttributeViewBlockAttr", {
    avID: '20241017094451-2urncs9',
    keyID: '20241017095436-2wlgb7o',
    rowID: '20241017094453-65uzx7e',
    cellID: '20241017100212-eqifwx8',
    value: {
            "number": {
                "content": 3
            }
        },
});

res

// type: select
let res = await request("/api/av/setAttributeViewBlockAttr", {
    avID: '20241017094451-2urncs9',
    keyID: '20241017094451-fu1pv7s',
    rowID: '20241017094453-65uzx7e',
    cellID: '20241017094455-9mj9255',
    value: {
            "mSelect": 
              [{"content":"Fiction3","color":"2"}]
            
        },
});

res

// type: mSelect
let res = await request("/api/av/setAttributeViewBlockAttr", {
    avID: '20241017094451-2urncs9',
    keyID: '20241017101851-kekovwz',
    rowID: '20241017094453-65uzx7e',
    cellID: '20241017102149-2jimfjh',
    value: {
            "mSelect": [{"content":"Fiction3"}]
        },
});

res
```

**Comment by Macavity** [comment]
The main challenge with this is the amount of code required for the different fields to correctly mimic the original functionality. I don't want this to become a maintenance nightmare.

**Comment by Achuan-2** [comment]
in siyuan v3.1.11, /api/av/setAttributeViewBlockAttr do not need cellID (see https://github.com/siyuan-note/siyuan/issues/12996)
and rowID is docID, for a doc added to the database
now, 
```js
// number
let res = await request("/api/av/setAttributeViewBlockAttr", {
    avID: '20241017094451-2urncs9',
    keyID: '20241017095436-2wlgb7o',
    rowID: '20241017094453-65uzx7e', // docID
    value: {
            "number": {
                "content": 3
            }
        },
});

res

// type: single select
let res = await request("/api/av/setAttributeViewBlockAttr", {
    avID: '20241017094451-2urncs9',
    keyID: '20241017094451-fu1pv7s',
    rowID: '20241017094453-65uzx7e', // docID
    value: {
            "mSelect": 
              [{"content":"Fiction3","color":"2"}]
            
        },
});

res

// type: multiple Select
let res = await request("/api/av/setAttributeViewBlockAttr", {
    avID: '20241017094451-2urncs9',
    keyID: '20241017101851-kekovwz',
    rowID: '20241017094453-65uzx7e', // docID
    value: {
            "mSelect": [{"content":"Fiction3"}]
        },
});

res
```

**Comment by Macavity** [comment]
Saving the data is the smallest problem, the main challenge is how to render the complex fields like Select or Relation.

**Comment by Achuan-2** [comment]
Saving the data is the smallest problem; the main challenge is how to render complex fields like Select or Relation.

I'm sorry, I'm not particularly knowledgeable about rendering. Can't the functionality of the property panel be reused?

**Comment by Achuan-2** [comment]
If you encounter difficulties, you can submit issue in the repo of SiYuan. The developer should be willing to provide help.

**Comment by Macavity** [comment]
Yes, it would make sense to make a proposal for this. But this is not an "issue" or but. Instead it would be a new feature for Siyuan - and then the discussions will take place if this actually makes sense or not.

**Comment by Achuan-2** [comment]
Great! Thank a lot for your contribution
