### ISSUE TITLE
some issues with the feature "Show empty properties"

### ISSUE THREAD

**Issue by QMike0** [Macavity/siyuan-database-properties-panel#16]
**Describe the bug**
1. When the feature "Show empty properties" is enabled, the attribute panel will not be shown at the beginning of the articles, which may be a bug.
  
![image](https://github.com/user-attachments/assets/e6e16574-79d9-4fb5-ba5a-15da99c07545)

2. Some issues with Chinese translation In the plugin settings interface: 
    - "Show empty properties" should be translated into "显示空值" or “显示空属性”
    - "(Experimental) Use to hide properties that have no value in the panel. Does not fully work with template properties, which contain html, or numbers, which often have the value "0"." should be "（试验性） 用于隐藏面板中没有值的属性。无法完全适用于模板列（包含html）或数字列（可能包含数值0）"

**Environment:**

- OS: Win 11
- Siyuan Version: v3.1.9
- Plugin Version: v0.4.2

**Comment by Macavity** [comment]
> When the feature "Show empty properties" is enabled, the attribute panel will not be shown at the beginning of the articles, which may be a bug.

Thank you for the bug report 👍 

I've actually reproduced the issue as well just now.
This table entry:
<img width="1434" alt="Screenshot 2024-10-22 at 08 51 02" src="https://github.com/user-attachments/assets/76a3794c-e9bb-4924-a128-002cfdd890f7">

Causes an error in the document page:
<img width="537" alt="Screenshot 2024-10-22 at 09 04 47" src="https://github.com/user-attachments/assets/a75b34af-0afb-49f6-bcfb-d59ac63466e8">

And secondly, thank you for helping me improve the chinese translation ❤️

**Comment by QMike0** [comment]
It seems that the first issue still exists in v 0.4.3
(Siyuan version: v3.1.10)
![image](https://github.com/user-attachments/assets/beccde5b-65c1-46fb-ae85-df1825ee87ba)

**Comment by Macavity** [comment]
@QMike0 
Which types of empty fields do you have there?

**Comment by Macavity** [comment]
I'll assume it was an asset field as I found another issue lurking in there which I fixed in [v0.4.4](https://github.com/Macavity/siyuan-database-properties-panel/releases/tag/v0.4.4).

Do you still have the issue?

**Comment by QMike0** [comment]
Now it could run normally, seems that the problem is caused by the asset field.
Thanks a lot!
