### ISSUE TITLE
The text column shows extra indentation.

### ISSUE THREAD

**Issue by Achuan-2** [Macavity/siyuan-database-properties-panel#20]
**Describe the bug**

![PixPin_2024-10-30_09-55-01](https://github.com/user-attachments/assets/11a9c790-aaf5-4f09-b68f-41f800eaf308)

**Environment:**

- OS: Windows
- Siyuan Version: v3.1.11
- Plugin Version: v0.4.4

**Comment by Achuan-2** [comment]
https://github.com/Macavity/siyuan-database-properties-panel/pull/29

**Comment by Macavity** [comment]
Solved with v0.5.2
