### ISSUE TITLE
Support displaying column icons.

### ISSUE THREAD

**Issue by Achuan-2** [Macavity/siyuan-database-properties-panel#21]
**Describe the idea**

![PixPin_2024-10-30_10-06-10](https://github.com/user-attachments/assets/c17b8130-611e-4996-9adc-a45b65f7b02a)

The icon currently displayed is still the default type icon.
![PixPin_2024-10-30_10-06-21](https://github.com/user-attachments/assets/363ad575-b33e-490a-93fa-9aa7c0357898)

**Comment by Macavity** [comment]
That's a great suggestion for an enchancement.
