### ISSUE TITLE
Template column display error

### ISSUE THREAD

**Issue by AvoidantPerDis** [Macavity/siyuan-database-properties-panel#5]
![image](https://github.com/user-attachments/assets/d61732d1-319f-4b7c-9465-756521e9521a)
可能是因为html？
还有多数据库应该搞个区分
![image](https://github.com/user-attachments/assets/9065e1f9-9025-403b-bca1-54086cc113e7)
其实我觉得直接把属性面板的扒下来最简单也不怎么需要维护
![image](https://github.com/user-attachments/assets/fcfd1fb1-3743-45df-9d1e-4af04d58219d)

**Comment by AvoidantPerDis** [comment]
另外我测试是只对文档起效吗？

**Comment by Macavity** [comment]
Can you please write in english? I can of course try to translate using DeepL, but it's not always easy. Let me first check if I have understood you correctly. 

> 还有多数据库应该搞个区分
> And there should be a distinction between multiple databases
How can a document belong to multiple databases? I don't see how that is possible.

> 其实我觉得直接把属性面板的扒下来最简单也不怎么需要维护
> Actually, I think it's easiest and less maintenance to just strip down the attribute panel's
That's what I did already, I have mostly reused the existing attribute panel code.

> 另外我测试是只对文档起效吗？
> Also is my test only working on documents?
What other types are there which could have this panel beside documents?

**Comment by Achuan-2** [comment]
in siyuan, a document can indeed be added to multiple database,  which enabling document reuse. This counts as a feature. So  you should  show the database title in attribute panel.
![PixPin_2024-10-12_21-54-21](https://github.com/user-attachments/assets/68d97cb4-6ffd-4810-9c9b-2f34058144b6)
![PixPin_2024-10-12_21-54-36](https://github.com/user-attachments/assets/2d6ed67c-130d-4c82-87d6-54a000cdefaf)

**Comment by Macavity** [comment]
Wow, I didn't know that. Thank you for sharing 🙇‍♂️ 

I'll keep this feature about html/template columns and create a new issue for supporting multiple databases.
