### ISSUE TITLE
Plugin reports error: undefined is not iterable (cannot read property Symbol

### ISSUE THREAD

**Issue by Achuan-2** [Macavity/siyuan-database-properties-panel#6]
![PixPin_2024-10-12_11-58-13](https://github.com/user-attachments/assets/9d01188e-95c2-4c6a-b16d-caed9c6537f0)

**Comment by Achuan-2** [comment]
很奇怪，我只有一个文档能显示数据库属性面板，其他文档都不可以

**Comment by loonghfut** [comment]
我一个也显示不出来
和你一样的报错

**Comment by Macavity** [comment]
> 很奇怪，我只有一个文档能显示数据库属性面板，其他文档都不可以
> It's strange that I only have one document that shows the database properties panel, and none of the others

I have actually identified an issue which causes the panel to not show on several occasions. `0.3.0` will improve this.

> 我一个也显示不出来
> 和你一样的报错

Ideally, can you create a small document which shows the error. Then export it as `sy.zip` and attach it to the ticket?

**Comment by Achuan-2** [comment]
Looking forward to your improvements, thank you very much for the plugin, I've been looking forward to the feature of displaying the properties panel directly on documents for a long time now!

**Comment by Macavity** [comment]
Should be solved in the latest version `0.3.2`

**Comment by Achuan-2** [comment]
Thanks, the problem is solved.
