### ISSUE TITLE
compatible document navigation plug-ins

### ISSUE THREAD

**Issue by Achuan-2** [Macavity/siyuan-database-properties-panel#7]
![PixPin_2024-10-12_20-47-07](https://github.com/user-attachments/assets/3d1a8371-43e2-4f76-9bfa-c92a897cf9f6)
能否兼容文档导航插件，属性面板放在下面，文档导航放在上面

**Comment by Macavity** [comment]
I have never used that plugin. I guess both attach themselves to the same container and whichever is called first will then be the first 🤔 

I will take a look and try to find if there is an easy solution.

**Comment by Achuan-2** [comment]
DOM
![PixPin_2024-10-13_16-59-07](https://github.com/user-attachments/assets/eb00638d-d41e-40b8-8dfd-2f01cbd61d92)

**Comment by Achuan-2** [comment]
On the other hand, I think the attributes panel should also be like the document navigation plug-in, behind the .property-top, because when I added the document to the flashcard review, the properties panel was also highlighted
![PixPin_2024-10-13_17-02-56](https://github.com/user-attachments/assets/76fb9445-cc94-4ff9-ab1c-de45eb947788)

**Comment by Achuan-2** [comment]
Hope div.plugin-database-properties-wrapper can behind .protyle-top
![PixPin_2024-10-13_17-14-51](https://github.com/user-attachments/assets/a15e585f-e6e5-4c10-a67a-0fa9fc117a91)

**Comment by Macavity** [comment]
Good idea and input. I'll try out what that looks like and if it's feasible.

**Comment by Macavity** [comment]
I've tried adding the HierarchyNavigate plugin and with the changes from `0.4.0` the order of the two plugins looks better. But it might just be luck on my side 🤷‍♂️ 

Can you confirm @Achuan-2?

**Comment by Achuan-2** [comment]
it looks great！
![PixPin_2024-10-13_23-57-56](https://github.com/user-attachments/assets/0746ebd9-97ec-4356-8ce3-3bf08bfe20a1)
